export const GET_ALLSTUDENTS = "GET_ALLSTUDENTS";
export const GET_STUDENT = "GET_STUDENT";
export const STUDENT_ERROR = "STUDENT_ERROR";

// export const GET_STUDENTS = "GET_STUDENTS";

//SuperAdmin
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const INSTITUTE_SUCCESS = "INSTITUTE_SUCCESS";

//PRINCIPAL
export const ADDBRANCH_SUCCESS = "ADDBRANCH_SUCCESS";
export const BRANCH_FAIL = "BRANCH_FAIL";
export const GETALLBRANCH_SUCCESS = "GETALLBRANCH_SUCCESS";
